cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET, POST, PUT, DELETE, PATCH
  allowed-headers: "*"
  allow-credentials: true
logging:
  level:
    org.hibernate.SQL: DEBUG
spring:
  application:
    name: roundest_kotlin
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DB}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none